# Generated by Django 5.1.6 on 2025-03-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_user_avatar_alter_course_image_alter_lesson_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='tags',
            field=models.ManyToManyField(to='courses.tag'),
        ),
    ]
